name: Website Deployment
on: [push]
jobs:

  deploy:
    name: Website Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Website
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/MyWebsite
          git pull origin main
          git status
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear
